In [1]:
import numpy as np

- Faster to read less bytes of memory
- No type checking when iterating through objects
- Has contiguous memory: SIMD Vector Processing (single instruction multiple data), Effective Cache Utilization

In [2]:
a = np.array([1, 2, 3], dtype=np.int32)
print("array a: ", a, "\ntype: ", type(a), "\ndtype: ", a.dtype,
      "\nshape: ", a.shape, "\nsize: ", a.size, "\nitemsize: ", a.itemsize,
      "\nnbytes: ", a.nbytes, "\nndim: ", a.ndim)

array a:  [1 2 3] 
type:  <class 'numpy.ndarray'> 
dtype:  int32 
shape:  (3,) 
size:  3 
itemsize:  4 
nbytes:  12 
ndim:  1


- [startIndex:endIndex:stepSize]

In [3]:
np.zeros((2, 3))
np.ones((2, 3))
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [4]:
np.full_like(a, 5)

array([5, 5, 5], dtype=int32)

In [5]:
np.random.rand(2, 3)

array([[0.61823206, 0.17962607, 0.85044687],
       [0.06164774, 0.6138815 , 0.85735239]])

In [6]:
np.random.randint(0, 10, (2, 3))

array([[1, 2, 1],
       [3, 9, 4]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
b = np.array([[1, 2, 3]])
np.repeat(b, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Be careful when copying arrays!!!

In [9]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3 4 5]
[100   2   3   4   5]


In [13]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(np.matmul(a, b), "\n\n", a.dot(b))

[[6. 6.]
 [6. 6.]] 

 [[6. 6.]
 [6. 6.]]


In [14]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [16]:
# Statistics
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(stats))
print(np.max(stats, axis=0))
print(np.sum(stats, axis=1))

1
[4 5 6]
[ 6 15]


In [17]:
# Vertically stacking vectors
v1 = np.array([4, 3, 2, 1])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# Horizontally stacking vectors
h1 = np.ones((2, 3))
h2 = np.zeros((2, 1))
np.hstack([h1, h2])

array([[1., 1., 1., 0.],
       [1., 1., 1., 0.]])

In [ ]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')  # Default dtype is float64
filedata = filedata.astype('int32')

In [ ]:
# Boolean masking and advanced indexing
filedata[filedata < 35] = 35

In [23]:
# You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [24]:
a[(a > 2) & (a < 8)]

array([3, 4, 5, 6, 7])

In [29]:
a = np.arange(11)
np.where(a < 5, a, 10*a)

array([  0,   1,   2,   3,   4,  50,  60,  70,  80,  90, 100])

Sources:
- https://www.youtube.com/watch?v=QUT1VHiLmmI